/******
 * Version        Date        Name        Description
 * =============================================================
 * V1.0         18.06.26    Developer 1   Add Method Implemented
*******/ 

/********
 * Name: Calculator2
 * Author: Abhra
 * Date: 18/06/2026
 ********/


public with sharing class Calculator2 {
    public Calculator2() {

    }
    public integer add (integer a, integer b){
        return a+b;
    }
    public integer sub (integer a, integer b){
        return a-b;
    }
}